#!/usr/bin/env bash
export BOT_TOKEN='998013377:AAEOuQ6VHZO-qgs4DLH9MmazFRWcbRAAKrc';
export DB_ID='YOUR_ID_HERE';
export DB_SECRET='YOUR_SECRET_HERE';
export DB_TOKEN='YOUR_TOKEN_HERE';
export NAVIGATION_ROOT='YOUR_PATH_HERE';
